on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
    merge_check:
       runs-on: ubuntu-latest
       steps:
        - name: Check if the pull request is mergeable to master
          run: |
                if [[ "$GITHUB_HEAD_REF" == 'uat' ]]; then exit 0; 
                else
                  echo "Only UAT branch can be merged " 
                  exit 1; 
                fi;
